### ISSUE TITLE
Message Deserialization 

### ISSUE THREAD

**Issue by Nestor212** [ktgilliam/LFAST_Comms#8]
In CommService.cc 
function: processMessage(CommsMessage *msg) {

line 154: msgObject = msgRoot["MountMessage"]

Should this be generalized for different clients? 
Ex. Primary Mirror Control client might be: msgObject =  msgRoot["PMCMessage"]?

**Comment by ktgilliam** [comment]
Yes it should, good catch - I will update today and report back.
